# Generated by Django 3.2.9 on 2022-11-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0038_alter_ventas_abono'),
    ]

    operations = [
        migrations.CreateModel(
            name='CadaBanco',
            fields=[
                ('id_auto', models.BigAutoField(primary_key=True, serialize=False)),
                ('total_bancos', models.BigIntegerField(default=0, null=True, verbose_name='total_bancos')),
                ('bancolombia_lottus', models.BigIntegerField(default=0, null=True, verbose_name='bancolombia_lottus')),
                ('bancolombia_stiven', models.BigIntegerField(default=0, null=True, verbose_name='bancolombia_stiven')),
                ('davivienda', models.BigIntegerField(default=0, null=True, verbose_name='davivienda')),
                ('nequi', models.BigIntegerField(default=0, null=True, verbose_name='nequi')),
                ('daviplata', models.BigIntegerField(default=0, null=True, verbose_name='daviplata')),
            ],
        ),
    ]
