# Generated by Django 3.2.9 on 2022-11-11 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0039_cadabanco'),
    ]

    operations = [
        migrations.AddField(
            model_name='recibodecaja',
            name='id_movimiento_bancos',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='inventario.bancos'),
        ),
    ]
